name: didpay
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  web5:
    git:
      url: https://github.com/TBD54566975/web5-dart.git
      path: packages/web5
      ref: main

  collection: ^1.18.0
  flutter_hooks: ^0.20.3  
  flutter_secure_storage: ^9.0.0
  hooks_riverpod: ^2.4.9
  http: ^1.1.2
  intl: ^0.18.1
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.2
  mobile_scanner: ^4.0.0
  qr_flutter: ^4.1.0
  device_info_plus: ^9.1.2
  auto_size_text: ^3.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.2

flutter:
  uses-material-design: true
  fonts:
      - family: IBMPlexMono
        fonts:
          - asset: assets/fonts/IBMPlexMono-Regular.ttf
          - asset: assets/fonts/IBMPlexMono-Medium.ttf
            weight: 500
          - asset: assets/fonts/IBMPlexMono-Bold.ttf
            weight: 700
          - asset: assets/fonts/IBMPlexMono-SemiBold.ttf
            weight: 600
